export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE"
}

export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE"
}

export const requestConstants = {
    ADD_REQUEST_REQUEST: "ADD_REQUEST_REQUEST",
    ADD_REQUEST_SUCCESS: "ADD_REQUEST_SUCCESS",
    ADD_REQUEST_FAILURE: "ADD_REQUEST_FAILURE"

}

export const responseConstants = {
    GET_ALL_RESPONSE_REQUEST: "GET_ALL_RESPONSE_REQUEST",
    GET_ALL_RESPONSE_SUCCESS: "GET_ALL_RESPONSE_SUCCESS",
    GET_ALL_RESPONSE_FAILURE: "GET_ALL_RESPONSE_FAILURE"

}